<?php

    // For a full list of all of the components that make up the SDK for PHP, see
    // https://developers.facebook.com/docs/php/reference

    try {
        $user = $fb->get('/me?fields=name');
    }
    catch(Facebook\Exceptions\FacebookResponseException $e) {
        echo 'Graph returned an error: ' . $e->getMessage();
        exit;
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
        // When validation fails or other local issues
        echo 'Facebook SDK returned an error: ' . $e->getMessage();
        exit;
    }

    $userName = $user->getDecodedBody();
    pr('Logged in as '. $userName['name']);
    pr('<br>');

    $storage = conf('app.storage');
    $campaign_ids = parse_ini_file($storage);

    try {
        $response = [];

        $message = '';
        $count = 0;
        foreach ($campaign_ids as $actId => $compaignIds) {
            foreach ($compaignIds as $compaignId) {
                set_time_limit(300);

                $id = substr($compaignId,5);
                if ('1' === $type) {
                    $message .= '[1] '. $compaignId ."\n";
                    $response[] = $fb->post( '/' . $id . '?status=ACTIVE');
                }
                elseif ('0' === $type) {
                    $message .= '[0] '. $compaignId ."\n";
                    $response[] = $fb->post( '/' . $id . '?status=PAUSED');
                }
                else {
                    echo 'bad ';
                    continue;
                }

                $count++;
                echo $count . ' ';
                ob_flush();
                flush();
                if (0 == $count % 5) {
                    sleep(240);
                }

            }
        }

        if ($message) {
            pr('<pre>'.$message.'</pre>');
            \MailHelper::send($message);
        }

    }
    catch(Facebook\Exceptions\FacebookResponseException $e) {
        echo 'Graph returned an error: ' . $e->getMessage();
        exit;
    }
    catch(Facebook\Exceptions\FacebookSDKException $e) {
        // When validation fails or other local issues
        echo 'Facebook SDK returned an error: ' . $e->getMessage();
        exit;
    }

